# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  # it is important that the name of this box is "default"
  config.vm.define :default do |vagrant_host|
    # Box name
    vagrant_host.vm.box = 'rhel-atomic-7'
    vagrant_host.vm.hostname = "rhel-atomic-7-docker-host"
    config.vm.synced_folder './', '/vagrant', type: 'rsync', disabled: true
    config.vm.synced_folder './', '/mnt/vagrant', type: 'rsync'
    config.nfs.functional = false

    vagrant_host.vm.provision 'shell', inline: "sudo systemctl stop docker > /dev/null 2>&1 || :" #in case this isn't first run
    vagrant_host.vm.provision 'shell', inline: "sudo groupadd docker > /dev/null 2>&1 || : "
    vagrant_host.vm.provision 'shell', inline: "sudo usermod -a -G docker vagrant"
    vagrant_host.vm.provision 'shell', inline: "sudo systemctl enable docker && sudo systemctl start docker"
    vagrant_host.vm.provision 'shell', inline: "sudo chown root:docker /var/run/docker.sock"
    vagrant_host.vm.provision 'shell', inline: "sudo systemctl enable docker && sudo systemctl start docker"

    # PLM additions
    # make sure that the Red Hat internal DNS is registered
    vagrant_host.vm.provision 'shell', inline: "sudo nmcli con mod 'Wired connection 1' ipv4.ignore-auto-dns yes && sudo nmcli con mod 'Wired connection 1' ipv4.dns '10.5.30.160 10.11.5.19 8.8.8.8' && sudo nmcli con up 'Wired connection 1'"

    # END
    
    # PLM additions 
    # allow access to CE (Kev's team) repo, to pull registry-ui
    vagrant_host.vm.provision 'shell', inline: "echo \"ADD_REGISTRY='--add-registry ce-registry.usersys.redhat.com' \n DOCKER_NETWORK_OPTIONS='-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock'\" | sudo tee --append /etc/sysconfig/docker > /dev/null"
    vagrant_host.vm.provision 'shell', inline: "sudo systemctl enable docker && sudo systemctl start docker"
    # END

    # PLM additions
    # Bring up Kubernetes
    vagrant_host.vm.provision 'shell', inline: "echo '[Unit]
Description=Kubernetes

[Service]
ExecStart=/mnt/vagrant/kube-cluster-up.sh
User=vagrant

[Install]
WantedBy=multi-user.target ' | sudo tee /etc/systemd/system/kubernetes.service > /dev/null"
    vagrant_host.vm.provision 'shell', inline: "sudo systemctl enable kubernetes && sudo systemctl start kubernetes"

    # END
    
    # PLM additions
    # Bring up the registry pods inside Kubernetes and expose ports to bare metal
    vagrant_host.vm.provision 'shell', inline: "echo '[Unit]
Description=Registry

[Service]
ExecStart=/mnt/vagrant/kube-pods-up.sh
User=vagrant

[Install]
WantedBy=multi-user.target ' | sudo tee /etc/systemd/system/registry.service > /dev/null"
    #
    vagrant_host.vm.provision 'shell', inline: "sudo systemctl enable registry && sudo systemctl start registry"
    

    config.vm.network "forwarded_port", guest: 5000, host: 5000
    config.vm.network "forwarded_port", guest: 5001, host: 5001
    #config.vm.network "forwarded_port", guest: 2375, host: 2375

    # END
  end
end

