[[byo]]
## Instructions for bringing your own laptop

### Install Virtual Box or virt-manger

### Install Vagrant

### Install the Red Hat Container Development Kit

You need to have installed your virtualization environment and Vagrant.

First, download the CDK from the instructor machine:

. Red Hat Container Tools <TODO>
. Red Hat Atomic Vagrant box for VirtualBox or Red Hat Atomic Vagrant box for libvirt (choose based on your virtualization env) <TODO>
+
TIP: If you are on Mac, the `util/cdk-install-mac` script will set up the CDK for you. Place both the cdk `zip` file and the RHEL Atomic `box` in the downloads directory.
+
All of the remaining steps need to be performed using the command-line.

. Unzip the `cdk.zip` file you downloaded in your home directory. This should create `~/cdk` (`/Users/username/cdk`)
+
----
$ cd
$ unzip ~/Downloads/cdk-1.0-0.zip
----
+
. Install additional Vagrant plugins for using Red Hat Vagrant boxes
+
The installation of the first plugin make take several minutes Vagrant may install some additional gem files as needed.
+
----
$ cd ~/cdk/plugins
$ ls -1 \*.gem
$ vagrant plugin install vagrant-registration-0.0.8.gem
$ vagrant plugin install vagrant-atomic-0.0.3.gem
----
+
Verify the plugins are installed:
+
----
$ vagrant plugin list
----
+
Add the RHEL Server and Red Hat Atomic Host boxes to Vagrant.
+
These are the configured virtual machine images that you downloaded a previous step. You will be using these for container development and testing.
+
----
$ vagrant box add --name rhel-atomic-7 ~/Downloads/rhel-atomic-virtualbox-7.1-0.x86_64.box
----
+
Verify that the boxes got installed:
+
----
$ vagrant box list
----
+
The box image files will be stored in your home directory under `~/.vagrant.d`. You will need adequate space there, approximately 2GB.
+
. Start up the RHEL Atomic CDK Vagrant Box
+
----
$ cd ~/cdk/components//rhel/rhel-with-docker/atomic-docker-host
$ vagrant up
----
+
At this point, if all is going well, you will be asked for a username and password for Red Hat subscription management in order to register the system and enable downloading from Red Hat repositories. Enter the username and password you use with the Red Hat Customer Portal.
+
----
==> default: Registering box with vagrant-registration…
default: Would you like to register the system now (default: yes)? [y|n] y
default: Subscriber username: <username>
default: Subscriber password:
----
+
You can check whether your Vagrant box is running with vagrant status. Note: you must be in same the directory where your Vagrant file is located.
+
----
$ vagrant status
----
+
Now you can ssh into your Red Hat Enterprise Linux CDK Vagrant box:
+
----
$ vagrant ssh
----
+
When you are done, exit the ssh session. To stop the Vagrant box:
+
----
$ vagrant halt
----
+
To view the status of all Vagrant boxes on your system and verify that your box was properly stopped, use vagrant global-status:
+
----
$ vagrant global-status
----
+
If, at some point you want to delete the created VM and free up the KVM/libvirt resources, use vagrant destroy. Your `Vagrantfile`, and the box image in `~/.vagrant.d` will remain allowing you to recreate a fresh version of the environment with a subsequent vagrant up.
+
----
$ vagrant destroy
----
+
Note: Do not delete the subdirectory `.vagrant` where Vagrant keeps per-machine state, without first using vagrant destroy to free up KVM/libvirt resources. If you no longer have the .vagrant subdirectory, you will need to use libvirt tools such as virt-manager (GUI) or virsh (command-line) to manually delete the resources that were created by Vagrant before you can bring a Vagrant box up with the same name.
+
After a vagrant destroy, you will be able to bring the Vagrant box up again in it’s original clean state.
+
You now have the Red Hat CDK software components successfully installed and can begin exploring container development.

#### Bring up your Docker and Kubernetes environment

In this lab, the docker host runs inside a Vagrant box that is running Red Hat Atomic Host. By default both docker and kubernetes are up and running.

. Change to the registry directory `cd lab`.
. Bring up the vagrant box `vagrant up`.
. SSH in to the vagrant box `vagrant ssh`.

TIP: If you are running this outside of the lab, and don't have `classroom.example.com` available in your DNS, you will need to define this. The lab VM includes support for adding this. If you are running the registry on your development machine, then run `export CLASSROOM_IP=<your public ip>` before running  `vagrant up` for the first time.

You are now running inside a docker and kubernetes environment.

#### Use the Docker host on your local box

Having brought up your Docker host, you may want to use Docker on your local machine:


. Allow the local Docker client to connect to the Docker host by running:
+
----
$ export DOCKER_HOST=127.0.0.1:2375 && unset DOCKER_CERT_PATH && unset DOCKER_TLS_VERIFY
----
+
. Check that you can access the Docker host by running `docker ps`.
. Connect your local filesystem to Docker. Open a new shell window, change to the lab directory, and run:
+
----
$ vagrant rsync-auto
----

### Starting Red Hat CDK environment
Red Hat CDK comes with a virtual machine that are optimized for running containers, called Red Hat Atomic. It uses Vagrant to manage the virtual machine and included boxes for VirtualBox and KVM (libvirt). The participants that uses a lab machine can run the labs without a virtual machine, since Red Hat Enterprise Linux 7.1 includes support for containers. However probably not all of the participants are using Red Hat Enterprise Linux as a Desktop at their workplace, so to give particpants as true real life experience as possible, they will use the same setup on the lab machines.

See <<byo>>,Bring Your Own Device Setup Guide>> for information on how to install the software on your Mac OS X(R), Windows(R) or Linux(R) desktop.


Step 1 - Create lab directory in your home directory and go into the directory::
+
[source,bash,numbered]
----
$ mkdir ~/lab && cd ~/lab
----
+
Step 2 - Download the Vagrant file for the labs to the `lab` directory::
+
[source,bash,numbered]
----
 $ wget -O Vagrantfile http://classroom.example.com/lab-setup/Vagrantfile
----
+
Step 3 - Start the Vagrant container::
+
[source,bash,numbered]
----
$ vagrant up
----


