# Instructor machine

## Environment

The instructor machine is provided as a Vagrantbox. To run the Vagrantbox you will need:

* Vagrant 1.7.2
* VirtualBox/lib-virt
* Red Hat CDK (Container Development Kit)
* RHEL Atomic image
* Checkout of lab git repo

More details on installing Vagrant, VirtualBox, the CDK and the RHEL Atomic image are provided in link:../byo.adoc[].

The Vagrantbox provides:

* A docker registry on port `5000`
* A docker registry UI on port `5001`
* A nexus repository, which caches all requests, on port `5003`
* An HTTP webserver providing the lab instructions, various git repos, and any binaries needed on port `5002`


## Start the `instructor` Vagrantbox

. Connect to the VPN or be on a Red Hat internal network.
. Install the `vagrant-reload` plugin:
+
----
vagrant plugin install vagrant-reload
----
. Change to the registry directory `cd instructor`.
. Bring up the vagrant box `vagrant up`.
. Wait for all the pods to come up and to populate. This can take a long while, as images need to be got from servers, neuxs needs to be populated with maven artifacts, git repos need to be cloned, and various images need adding to the docker registry. To check the status, run `kubectl get pods`: the `registry`, `nexus` and `www` pods should show `Running` and the `registry-populate`, `nexus-populate` and `www-populate` pods should show `Suceeded`.
. Visit <http://localhost:5002> and explore the services and assets.
