# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  # it is important that the name of this box is "default"
  config.vm.define :default do |vagrant_host|
    # Box name
    vagrant_host.vm.box = 'rhel-atomic-7'
    vagrant_host.vm.hostname = "rhel-atomic-7-docker-host"
    
    config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
      v.memory = 2048
    end
    
    config.vm.synced_folder './', '/vagrant', type: 'rsync', disabled: true
    config.vm.synced_folder './', '/mnt/vagrant', type: 'rsync'
    config.nfs.functional = false


    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook-lab.yaml"
    end

    vagrant_host.vm.provision 'shell', inline: "echo 'Run:\n  export DOCKER_HOST=127.0.0.1:2375 && unset DOCKER_CERT_PATH && unset DOCKER_TLS_VERIFY\nto use docker on the host machine'"

    config.vm.network "forwarded_port", guest: 2375, host: 2375

    # END
  end
end

